config/routes.rb
Siphon::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root to: "reformattings#index"

  resources :reformattings
  resources :microfilm_reels
  resources :microfilm_print_slips do
    member do
      get "record_targets"
    end
  end

  get :reformattings_print_slips, to: 'reformatting_print_slips#print'
end

app/models/microfilm_reel.rb
class MicrofilmReel < ActiveRecord::Base

  # the state_machine gem is no longer maintained and initial values are broken in rails 4.2. This is a work around.
  # see https://github.com/pluginaweek/state_machine/issues/334
  after_initialize :set_initial_status
  def set_initial_status
    self.status ||= :open
  end

  has_many :microfilm_volumns, -> { order(:order).includes(:reformatting_book) }


  state_machine :status, :initial => :open do

    event :close do
      transition [:open] => :closed
    end


    event :reopen do
      transition [:closed] => :open
    end


    state :open
    state :closed
  end


end

app/controllers/microfilm_reels_controller.rb
class MicrofilmReelsController < ApplicationController

  def index
    MicrofilmReel
    @list = MicrofilmReelList.new(self)
  end

  def new
    @reel = NewMicrofilmReelForm.build_from_params(self)
  end

  def create
    @reel = NewMicrofilmReelForm.build_from_params(self)

    if @reel.create!()
      flash[:notice] = "Microfilm Reel Created"
      redirect_to edit_microfilm_reel_path(@reel.microfilm_reel)
    else
      flash[:error] = "There has been an error saving the reel.  Please review the form and try again."
    end
  end

  def edit
    @reel = EditMicrofilmReelForm.build_from_params(self)
  end

  def update
    @reel = EditMicrofilmReelForm.build_from_params(self)

    if @reel.add_volumns!()
      flash[:notice] = "Microfilm Reel Saved"
      if @reel.closed?
        redirect_to microfilm_reels_path(status: 'closed')
      else
        redirect_to microfilm_reels_path()
      end
    else
      flash[:error] = "There has been an error saving the reel.  Please review the form and try again."
    end
  end
end

app/views/microfilm_reels/edit.html.erb
<% content_for(:content_title) do %>
  <h1><%= @reel.reel_name %></h1>
<% end %>

<%
breadcrumb([ link_to('Microfilm Reels', microfilm_reels_path()), "#{@reel.reel_name}"])
%>


<h3>Volumes</h3>

<%= simple_form_for @reel, url: microfilm_reel_path(@reel.microfilm_reel), method: :put do | f | %>

  <ol id="volume_list">
    <% @reel.current_volumns.each do | r | %>
      <li><span><input type="text" name="edit_microfilm_reel_form[volumns][<%= r.reformatting_book_id %>]" value="<%= r.title %>" class="span8"></span> - <a href="#" class="delete_volume">x</a></li>
    <% end %>
  </ol>


  <div>
    <%= select_tag :possible_volumes, options_from_collection_for_select(@reel.potential_volumns, :id, :title), include_blank: true %>
    <button class="btn add_volume_button">Add Volumne</button>
  </div>

  <div class="form-actions">
    <%= f.input :complete, as: :boolean, inline_label: "This reel is full", label: false %>

    <%= f.button :submit, "Save", :class => 'btn-primary' %>
  </div>

<% end %>

<div style="display:none;" class="li_template">
  <li id="ID"><span><input type="text" name="edit_microfilm_reel_form[volumns][ID]" value="TITLE" class="span8"></span> - <a href="#" class="delete_volume">x</a></li>
</div>

app/views/microfilm_reels/index.html.erb
<% content_for(:content_title) do %>
  <h1>Microfilm Reels</h1>
<% end %>

<% content_for(:content_title_links) do %>
  <%= link_to "New Microfilm Reel", new_microfilm_reel_path(), class: 'btn btn-primary' %>
<% end %>

<%
breadcrumb(['Microfilm Reels'])
%>


<div class="tabbable tabs-top">
  <ul class="nav nav-tabs">
    <li class="<%= @list.tab_css_class('open') %>">
      <%= link_to 'Open', microfilm_reels_path(status: 'open'), class: "tab #{@list.tab_css_class('open')}" %>
    </li>
    <li class="<%= @list.tab_css_class('closed') %>">
      <%= link_to 'Closed', microfilm_reels_path(status: 'closed'), class: "tab #{@list.tab_css_class('closed')}" %>
    </li>
  </ul>
</div>


<table class="table table-striped find-resources datatable">
  <thead>
    <tr>
      <th>Storage Number</th>
      <th># Items</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @list.reels.each do | r |  %>
      <tr>
        <td><%= link_to r.name, edit_microfilm_reel_path(r) %></td>
        <td><%= r.microfilm_volumns.size %></td>
        <td>
          <%= link_to 'Print Reel Contents', microfilm_print_slip_path(r.id), target: 'blank' %></a> |
          <%= link_to 'Print Record Target', record_targets_microfilm_print_slip_path(r.id), target: 'blank' %></a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/microfilm_reels/new.html.erb
<% content_for(:content_title) do %>
  <h1>New Microfilm Reels</h1>
<% end %>

<%
breadcrumb([ link_to('Microfilm Reels', microfilm_reels_path()), 'New Microfilm Reel'])
%>


<div class="four coulmns">
<%= simple_form_for @reel.microfilm_reel do | f | %>

  <%= f.input :name, required: true %>

  <div class="form-actions">
    <%= f.button :submit, "Save", :class => 'btn-primary' %>
  </div>

<% end %>
</div>