config/routes.rb
Siphon::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root to: "reformattings#index"

  resources :reformattings
  resources :microfilm_reels
  resources :microfilm_print_slips do
    member do
      get "record_targets"
    end
  end

  get :reformattings_print_slips, to: 'reformatting_print_slips#print'
end

app/models/reformatting_print_slips.rb
class ReformattingPrintSlips

  attr_accessor :books

  def self.build_from_params(controller)
    items = ReformattingBook.find(controller.params[:ids].split(","))

    self.new(items)
  end


  def initialize(reformattings_to_print)
    @books = reformattings_to_print
  end


end

app/controllers/reformatting_print_slips_controller.rb
class ReformattingPrintSlipsController < ApplicationController


  def print
    @print_slips = ReformattingPrintSlips.build_from_params(self)

    render layout: 'print'
  end

end

app/views/reformatting_print_slips/_slip.html.erb
<p>  <%= Time.now.to_date.to_s(:long_ordinal) %> </p>
<h4 style="margin-bottom: 0"><%= truncate(book.title, length: 60) %></h4>
<p style="margin-top: 5px">
  <%= book.call_number %><br>
  System Number: <%= book.document_number %><br>
</p>
<p>
  Loans Since 1998: <%= book.number_of_loans %><br />
  ND Holdings of this Edition: <%= book.nd_holdings %><br />
  WorldCat Holdings of this Edition: <%= pluralize(book.number_of_libraries, 'library', 'libraries') %></p>
  Internet Archive: <%= print_reformatting_url(book.internet_active_url) %><br />
  Hathi Trust: <%= print_reformatting_url(book.hathi_trust_url) %>
</p>

<strong>Notes:</strong>
<%= simple_format(book.notes_for_selector) %>

<hr>

<p><strong>Selector Decision</strong></p>

<p>Preservation Surrogate <small>(Select 1)</small></p>
<ul class="unstyled" style="padding-bottom: 20px;">
  <li><%= image_tag 'check-box-empty.gif' %> Digitize and Print Reproduction</li>
  <li><%= image_tag 'check-box-empty.gif' %> Digitize</li>
  <li><%= image_tag 'check-box-empty.gif' %> No Digitization or Reprint</li>
</ul>

<p>Preservation of Original Volume <small>(Select 1)</small></p>
<ul class="unstyled" style="padding-bottom: 20px;">
  <li><%= image_tag 'check-box-empty.gif' %> Return to Shelf (Will Box as Needed)</li>
  <li><%= image_tag 'check-box-empty.gif' %> Retain and Transfer to Special Collections (Will box as needed)</li>
  <li><%= image_tag 'check-box-empty.gif' %> Withdraw</li>
</ul>

app/views/reformatting_print_slips/print.html.erb
<%
i = 0
%>
<% @print_slips.books.each do | book | %>
  <div class="page-break">
    <%= render partial: 'slip', locals: { book: book } %>
  </div>

  <% i += 1 %>
<% end %>