config/routes.rb
Siphon::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root to: "reformattings#index"

  resources :reformattings
  resources :microfilm_reels
  resources :microfilm_print_slips do
    member do
      get "record_targets"
    end
  end

  get :reformattings_print_slips, to: 'reformatting_print_slips#print'
end

app/models/reformatting_form.rb
class ReformattingForm

  class StatusNotFound < Exception; end

  attr_accessor :book

  def initialize(controller)
    @controller = controller
    @book = get_book(@controller.params[:id])

    verify_in_process!
  end


  def status_form
    @status_form ||= case @book.status
      when 'inprocess'
        ReformattingPrepareForm.new(@book, @controller.params)
      when 'prepared'
        ReformattingDecisionForm.new(@book, @controller.params)
      when 'decisioned'
        ReformattingCompleteForm.new(@book, @controller.params)
      when 'complete'
        ReformattingCompletedForm.new(@book, @controller.params)
      else
        raise StatusNotFound.new("invalid book status")
      end
  end


  def section1
    status_form.section1
  end


  def section2
    status_form.section2
  end


  def section3
    status_form.section3
  end


  def send_to_next_step
    status_form.send_to_next_step
  end


  def send_back_step
    @book.back
  end


  private

    def get_book(id)
      ReformattingBook.find(id)
    end


    def verify_in_process!
      if @book.start
        @book.save!
      end
    end
end

app/controllers/reformattings_controller.rb
class ReformattingsController < ApplicationController


  def index
    @reformatting_list = ReformattingList.new(self)
  end


  def create
    ReformattingBook.test_book.save!

    redirect_to reformattings_path
  end


  def edit
    @form = ReformattingForm.new(self)
  end


  def update
    @form = ReformattingForm.new(self)

    if params[:goto_previous_step]
      if @form.send_back_step
        flash[:success] = "Moved back to #{@form.book.status}"
        redirect_to edit_reformatting_path(@form.book)
      else
        flash[:error] = "Unable to go back to previous status"
        render :edit
      end
    else
      if @form.send_to_next_step
        flash[:success] = "Saved Step"
        redirect_to edit_reformatting_path(@form.book)
      else
        flash[:error] = "Your form submission has errors in it.  Please correct them and resubmit."
        render :edit
      end
    end

  end

end

app/helpers/reformatting_helper.rb
module ReformattingHelper

  def link_to_reformatting_url(url)
    puts url.inspect
    return "No" if !url || url.empty?
    url = "http://#{url}" if !url.match(/^http[s]?:\/\//)

    link_to('Yes', url, target: '_blank')
  end


  def print_reformatting_url(url)
    return "No" if !url || url.empty?
    url
  end
end

app/views/reformattings/_book_header.html.erb
  <h1><%= h book.title %> <small><%= book.creator_contributor %></h1>
  <hr>
<%
breadcrumb([link_to('Reformatting Books', reformattings_path), book.title])
%>

app/views/reformattings/_complete_form.html.erb
<h3>Actions</h3>
<p class="form-help">
  Indicate that the selector decisions have been completed.
</p>

<%= simple_form_for book_form, :url => reformatting_path(book_form.id), :method => 'put' do | f | %>
  <% no_actions = true %>
  <% book_form.decision_fields.each do | field | %>
    <% if book_form.book.send(field) %>
      <% no_actions = false %>
      <%= f.input "#{field}_completed", as: :boolean, inline_label: field.to_s.titleize, label:false %>
    <% end %>
  <% end %>


  <% if no_actions %>
    <strong> There are no decisions to be recorded.  Press complete to continue. </strong>
  <% end %>

  <div class="form-actions">
    <%= f.button :submit, "Complete", :class => 'btn-primary' %>
  </div>
<% end %>

app/views/reformattings/_complete_info.html.erb
<h3>Actions</h3>

<ul class="unstyled">
<% book_form.decision_fields.each do | field | %>
  <% if book_form.book.send(field) %>
    <li><i class="icon icon-check"></i> <%= field.to_s.gsub("_completed", "").titleize %></li>
  <% end %>
<% end %>
</ul>

<% if book_form.book.status == 'complete' %>
  <%= simple_form_for book_form, :url => reformatting_path(book_form.id), :method => 'put' do | f | %>
    <%= hidden_field_tag 'goto_previous_step', 1 %>
    <%= f.submit "Go back a step" %>
  <% end %>
<% end %>

app/views/reformattings/_decision_form.html.erb
<% content_for(:content_title_links) do %>
  <%= link_to 'Print Book Slip', reformattings_print_slips_path(ids: book_form.id), class: 'btn btn-success', target: 'blank' %>
<% end %>
<h3>Selector Descision</h3>
<p class="form-help">
  Record the Selector Decision
</p>
<%= simple_form_for book_form, :url => reformatting_path(book_form.id), :method => 'put' do | f | %>

  <h4>Preservation of Surrogate</h4>
  <%= f.input :digital_and_paper_output, as: :boolean, inline_label: 'Digital and Print Reproduction', label:false %>
  <%= f.input :digital, as: :boolean, inline_label: 'Digitize only', label:false %>
  <%= f.input :no_action, as: :boolean, inline_label: 'No Action', label:false %>

  <h4>Preservation of the Original</h4>
  <%= f.input :retain, as: :boolean, inline_label: 'Retain', label:false %>
  <%= f.input :retain_and_transfer, as: :boolean, inline_label: 'Retain & Transfer to Special Collections', label:false %>
  <%= f.input :withdraw, as: :boolean, inline_label: 'Withdraw', label:false %>

  <%= f.input :notes_from_selector, as: :text %>

  <div class="form-actions">
    <%= f.button :submit, "Decisioned", :class => 'btn-primary' %>
  </div>
<% end %>

app/views/reformattings/_decision_info.html.erb
<% content_for(:content_title_links) do %>
  <%= link_to 'Print Book Slip', reformattings_print_slips_path(ids: book_form.id), class: 'btn btn-success', target: 'blank' %>
<% end %>
<h3>Selector Decision</h3>

<ul class="unstyled">

  <% if book_form.book.digital_and_paper_output %>
    <li><i class="icon icon-check"></i> Digitize and Print Reproduction</li>
  <% end %>

  <% if book_form.book.digital %>
    <li><i class="icon icon-check"></i> Digitize Only</li>
  <% end %>

  <% if book_form.book.no_action %>
    <li><i class="icon icon-check"></i> No Action</li>
  <% end %>

  <% if book_form.book.retain %>
    <li><i class="icon icon-check"></i> Retain</li>
  <% end %>

  <% if book_form.book.retain_and_transfer %>
    <li><i class="icon icon-check"></i> Retain and Transfer to Special Collections</li>
  <% end %>

  <% if book_form.book.withdraw %>
    <li><i class="icon icon-check"></i> Withdraw</li>
  <% end %>

  <% if book_form.book.photodup %>
    <li><i class="icon icon-check"></i> Photoduplication</li>
  <% end %>

  <% if book_form.book.microfilm_nd %>
    <li><i class="icon icon-check"></i> Microfilm ND</li>
  <% end %>

  <% if book_form.book.digital_link %>
    <li><i class="icon icon-check"></i> Digital Link</li>
  <% end %>

  <% if book_form.book.purchase_reprint %>
    <li><i class="icon icon-check"></i> Purchase Reprint</li>
  <% end %>

  <% if book_form.book.purchase_microfilm %>
    <li><i class="icon icon-check"></i> Purchase Reprint</li>
  <% end %>

  <% if book_form.book.return_to_shelf %>
    <li><i class="icon icon-check"></i> Return to Shelf</li>
  <% end %>

  <% if book_form.book.box %>
    <li><i class="icon icon-check"></i> Send to Special Collections</li>
  <% end %>


  <% if book_form.book.send_to_special_collections %>
    <li><i class="icon icon-check"></i> Send to Special Collections</li>
  <% end %>

  <% if book_form.book.fund_code.present? %>
    <li>Fund Code: <%= book_form.book.fund_code %></li>
  <% end %>
</ul>

<strong>Notes From Selector</strong>
<%= simple_format(book_form.book.notes_from_selector) %>

<% if book_form.book.status == 'decisioned' %>
  <%= simple_form_for book_form, :url => reformatting_path(book_form.id), :method => 'put' do | f | %>
    <%= hidden_field_tag 'goto_previous_step', 1 %>
    <%= f.submit "Go back a step" %>
  <% end %>
<% end %>

app/views/reformattings/_prepare_form.html.erb
<h3>Decisioning Information</h3>

<p class="form-help">
  Enter information for the selector to make a decision.
</p>

<%= simple_form_for book_form, :url => reformatting_path(book_form.id), :method => 'put' do | f | %>

  <%= f.input :nd_holdings %>

  <%= f.input :number_of_loans %>

  <%= f.input :number_of_libraries %>

  <%= f.input :hathi_trust_url %>

  <%= f.input :internet_active_url %>

  <%= f.input :notes_for_selector do %>
    <%= f.input_field :notes_for_selector, as: "text", rows: 3, style: "width: 100%" %>
  <% end %>

  <div class="form-actions">
    <%= f.button :submit, "Ready for Selector", :class => 'btn-primary' %>
  </div>
<% end %>

app/views/reformattings/_prepare_info.html.erb
<h3>Decisioning Information</h3>

<dl class="dl-horizontal">
    <dt>ND Holdings:</dt>
    <dd><%= book_form.book.nd_holdings %>&nbsp;</dd>

    <dt>Number of Loans:</dt>
    <dd><%= book_form.book.number_of_loans %>&nbsp;</dd>

    <dt>Number of Libraries:</dt>
    <dd><%= book_form.book.number_of_libraries %>&nbsp;</dd>

    <dt>Hathi Trust:</dt>
    <dd><%= link_to_reformatting_url(book_form.book.hathi_trust_url) %>&nbsp;</dd>

    <dt>Internet Archive:</dt>
    <dd><%= link_to_reformatting_url(book_form.book.internet_active_url) %>&nbsp;</dd>

</dl>
<strong>Notes For Selector:</strong>
<%= simple_format(book_form.book.notes_for_selector) %>

<% if book_form.book.status == 'prepared' %>
    <%= simple_form_for book_form, :url => reformatting_path(book_form.id), :method => 'put' do | f | %>
      <%= hidden_field_tag 'goto_previous_step', 1 %>
      <%= f.submit "Go back a step" %>
    <% end %>
<% end %>

app/views/reformattings/edit.html.erb
<%= render partial: 'book_header', locals: { book: @form.book } %>

<div class="two columns">
  <h4>Useful Links</h4>
  <ul class="unstyled">
    <li><%= FrbrGroupSearchLink.new(@form.book.frbr_group_id, @form.book.title).link %></li>
    <li><%= WorldCatOclcNumberLink.new(@form.book.oclc_number).link %></li>
    <li><%= HathiTrustSearchLink.new(@form.book.title).link %></li>
    <li><%= InternetArchiveSearchLink.new(@form.book.title).link %></li>
  </ul>
  <hr>
  <dl>
    <dt>Publisher</dt>
    <dd><%= @form.book.publisher %></dd>
    <dt>Call Number</dt>
    <dd><%= @form.book.call_number %></dd>
    <dt>Barcode</dt><dd><%= @form.book.barcode %></dd>
    <dt>System Number</dt><dd><%= @form.book.document_number.rjust(9, '0') %></dd>
    <dt>Status</dt><dd><%= @form.book.status %></dd>
  </dl>

</div>

<div class="four columns">
  <%= render @form.section1 %>
</div>
<div class="one column">
  &nbsp;
</div>
<div class="four columns">
  <%= render @form.section2 %>
</div>
<div class="twelve columns">
  <%= render @form.section3 %>
</div>

app/views/reformattings/index.html.erb
<% content_for(:content_title) do %>
  <h1>Reformatting Books</h1>
<% end %>

<%
breadcrumb(['Reformatting Books'])
%>


<div class="tabbable tabs-top">
  <ul class="nav nav-tabs">
    <li class="<%= @reformatting_list.tab_css_class('new') %>">
      <%= link_to 'New', reformattings_path(status: 'new'), class: "tab #{@reformatting_list.tab_css_class('new')}" %>
    </li>
    <li class="<%= @reformatting_list.tab_css_class('inprocess') %>">
      <%= link_to 'Inprocess', reformattings_path(status: 'inprocess'), class: "tab #{@reformatting_list.tab_css_class('inprocess')}" %>
    </li>
    <li class="<%= @reformatting_list.tab_css_class('prepared') %>">
      <%= link_to 'Prepared', reformattings_path(status: 'prepared'), class: "tab #{@reformatting_list.tab_css_class('prepared')}" %>
    </li>
    <li class="<%= @reformatting_list.tab_css_class('decisioned') %>">
      <%= link_to 'Decisioned', reformattings_path(status: 'decisioned'), class: "tab #{@reformatting_list.tab_css_class('decisioned')}" %>
    </li>
    <li class="<%= @reformatting_list.tab_css_class('complete') %>">
      <%= link_to 'Completed', reformattings_path(status: 'complete'), class: "tab #{@reformatting_list.tab_css_class('complete')}" %>
    </li>
    <li class="<%= @reformatting_list.tab_css_class('all') %>">
      <%= link_to 'All', reformattings_path(status: 'all'), class: "tab #{@reformatting_list.tab_css_class('complete')}" %>
    </li>
  </ul>

</div>


<table class="table table-striped find-resources datatable">
  <thead>
    <tr>
      <th>Title</th>
      <th>Volume</th>
      <th>Call Number</th>
      <th>Barcode</th>
      <th>System Number</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @reformatting_list.books.each do | book | %>
      <tr>
        <td><%= link_to book.title, edit_reformatting_path(book) %></td>
        <td><%= book.aleph_description %></td>
        <td><%= book.call_number %></td>
        <td><%= book.barcode %></td>
        <td><%= book.document_number %></td>
        <td><%= book.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>