config/routes.rb
Siphon::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root to: "reformattings#index"

  resources :reformattings
  resources :microfilm_reels
  resources :microfilm_print_slips do
    member do
      get "record_targets"
    end
  end

  get :reformattings_print_slips, to: 'reformatting_print_slips#print'
end

app/views/layouts/_include_ssi.html.erb
<% cache("ssi/#{active_branch_code}#{filepath}", :expires_in => 1.day) do %>
  <!-- <%= "#{active_branch_code}#{filepath} cache: #{Time.now.to_s}" %> -->
  <%= raw read_ssi_file(filepath) %>
<% end %>

app/views/layouts/_main_nav.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <a class="brand" href="/">Siphon</a>
    <ul class="nav">
      <li><%= link_to 'Reformatting Books', reformattings_path() %></li>
      <li><%= link_to 'Microfilm Reels', microfilm_reels_path() %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Hesburgh Library Reformatting</title>
    <meta name="description" content="Information resources and collections of the Hesburgh Libraries, University of Notre Dame." />

    <meta name="viewport" content="width=device-width">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="shortcut icon" sizes="128x128" href="http://library.nd.edu/icons/favicon-152.png">


    <%= hesburgh_stylesheet_link_tag    "admin", "index.css", :media => "all" %>

    <%= stylesheet_link_tag    "application", :media => "all" %>

    <%= hesburgh_javascript_include_tag "admin", "index.js" %>
    <%= javascript_include_tag "application" %>

    <%= csrf_meta_tags %>

  </head>
  <body>
    <div class="frame" id="frame">
      <div class="row header">
        <div class="twelve columns">
          <h2>Reformatting</h2>
        </div>
      </div>
      <div class="row menu">
        <div class="twelve columns">
          <%= render partial: '/layouts/main_nav' %>
        </div>
      </div>

      <div class="row content">
        <div class="frame">
          <div class="row breadcrumb hide-on-phones">
            <%
              if !content_for?(:breadcrumb)
                breadcrumb()
              end
            %>
            <div class="twelve columns">
              <p><%= content_for(:breadcrumb) %></p>
            </div>
          </div>
          <% if content_for?(:left_column) %>
            <div class="three columns">
              <%= content_for(:left_column) %>
            </div>
          <% end %>
          <%= display_notices %>
          <%
          content_width = 12
          if content_for?(:left_column)
            content_width -= 3
          end
          if content_for?(:right_column)
            content_width -= 4
          end
          if content_for?(:right_column_wide)
            content_width -= 5
          end
          %>
          <div class="<%= number_to_word(content_width) %> columns">
            <div id="pg-title">
              <% if content_for?(:content_title_links) %>
                <div class="pull-right">
                  <%= content_for(:content_title_links) %>
                </div>
              <% end %>
              <%= content_for(:content_title) %>
            </div>

            <%= yield %>

          </div>
          <% if content_for?(:right_column) %>
            <div class="four columns">
              <%= content_for(:right_column) %>
            </div>
          <% end %>
          <% if content_for?(:right_column_wide) %>
            <div class="five columns">
              <%= content_for(:right_column_wide) %>
            </div>
          <% end %>
        </div>

      </div>

    </div>
  </body>
</html>

app/views/layouts/print.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Hesburgh Library Reserves</title>
    <meta name="description" content="Information resources and collections of the Hesburgh Libraries, University of Notre Dame." />

    <meta name="viewport" content="width=device-width">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="shortcut icon" sizes="128x128" href="http://library.nd.edu/icons/favicon-152.png">

    <%= stylesheet_link_tag    "hesburgh_assets/admin/1.0/index.css", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <style>
/*      @media print { */
        .master_negative {
          height:612px;
        }
        .master_negative h1 {
          padding-top: 200px;
          text-align: center;
          font-size:5em;
          margin:0;
          line-height: 70px;
        }

        .volumn_page {
        }

        .record_target {

        }

        .page_break {
          page-break-after: always;
        }

        .record_target h1 {
          font-size: 1.75em;
          text-align: center;
          margin: 2px;
        }

        .record_target h2 {
          font-size: 1.33em;
          margin: 2px;
        }

        .record_target h3 {
          font-size: 1em;
          text-align: center;
          margin: 2px;
        }

        .record_target pre {
          border: none;
          background-color: #fff;
          line-height: 9px;
          font-size: 10px;
        }

        .print hr {
          margin: 5px;
        }

        h2 {
          font-size:2em;
          text-align: center;
        }

        ol li {
          line-height: 1.5em;
          font-size: 16px;
        }

        .volumn_page h3 {
          font-size:3em;
          padding-top: 100px;
          min-height: 250px;
        }

        .volumn_page h4 {
          font-size: 2.5em;
        }

/*      } */
<% if @landscape %>
      @page {
        size: landscape;
      }
<% end %>
      body {
        background-color: white
      }

    </style>

  </head>
  <body class="print">

    <%= yield %>

  </body>
</html>